on: 
  workflow_dispatch:
    inputs:

name: Build  
jobs:
  build-android:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      
      - name: Install npm dependencies
        run: npm install
        
      - name: Build Android Release
        run: cd android && ./gradlew assembleRelease
        
      - name: Read package.json
        uses: dutscher/read-package-json-endpoint-actions@v1.33.7
        id: package-json-endpoint

      - name: Show version number
        run: echo "${{ steps.package-json-endpoint.outputs.endpoint }}"

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: "apkP-${{ steps.package-json-endpoint.outputs.endpoint }}.apk"
          path: android/app/build/outputs/apk/release/

      - name: Create Github Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "android/app/build/outputs/apk/release/app-release.apk"
          tag: "${{ steps.package-json-endpoint.outputs.endpoint }}"
          replacesArtifacts: false
          token: ${{ secrets.GITHUB_TOKEN }}
          allowUpdates: true
